"""
Insight Generator Facade (Clinical Decision Support - Educational)
==================================================================
Master facade coordinating narrative health summaries, wellness recommendations,
lifestyle suggestions, and educational risk overviews.
"""
from typing import List, Dict, Any
from app.models.models import Vitals, Medication
from app.insights.summary_generator import summary_generator
from app.insights.recommendation_engine import insights_recommendation_engine
from app.insights.risk_summary import risk_summary_generator

DISCLAIMER = (
    "DISCLAIMER: The health score and insights generated by this application are for "
    "informational and educational purposes only. This is not an alternative to licensed "
    "clinical care, diagnosis, or therapy. Please consult your primary physician or doctor "
    "before initiating, altering, or terminating any therapies."
)


class InsightGenerator:
    """
    Produces human-readable educational insights from analytics data.
    """

    def generate_ai_insights(
        self,
        vitals: List[Vitals],
        medications: List[Medication],
        bp_analytics: Dict[str, Any] = None,
        weight_analytics: Dict[str, Any] = None,
        sugar_analytics: Dict[str, Any] = None,
        risk_profile: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        """
        Generates comprehensive educational summary narratives from pre-computed analytics.
        """
        summary_lines = summary_generator.generate_narrative_summary(
            vitals, medications, bp_analytics, weight_analytics, sugar_analytics
        )
        wellness, lifestyle = insights_recommendation_engine.generate_tips_and_suggestions(
            vitals, medications, weight_analytics
        )
        risk_overview = risk_summary_generator.generate_risk_overview(risk_profile or {}) if risk_profile else {}

        return {
            "health_summary": " ".join(summary_lines),
            "summary_bullet_points": summary_lines,
            "wellness_recommendations": wellness,
            "lifestyle_suggestions": lifestyle,
            "risk_overview": risk_overview,
            "disclaimer": DISCLAIMER,
            "module_name": "Clinical Decision Support (Educational) / Health Insights Engine"
        }


insight_generator = InsightGenerator()
